# Generated by Django 3.1.7 on 2021-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.TextField(max_length=300),
        ),
    ]
