# Generated by Django 3.1.7 on 2021-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20210406_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
